"use client";

import "./styles/global.css";

import { Inter } from "next/font/google";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { z } from "zod";

import { ThemeProvider } from "@/components/theme-provider";
import { FormSchema } from "@/lib/types";

import Providers from "./provider";

import type { Metadata } from "next";
import { Navigation, Search } from "@/components/organisms";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const route = useRouter();
  const searchParams = useSearchParams();
  const pathName = usePathname();

  const pageNumber = searchParams.get("page");

  function onSearchSubmit(data: z.infer<typeof FormSchema>) {
    route.push(`/${data.type}?keyword=${data.keyword}&page=${pageNumber}`);
  }

  const currentPath = pathName.replace("/", "");

  /**
   * Change route and reset page number to one
   *
   * @param {string} category
   */
  const handleNavigationChange = (category: string) => {
    route.push(`/${category}?page=1`);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <nav className="flex w-full h-20 border-b">
              <div className="max-w-6xl w-full flex flex-wrap items-center justify-between mx-auto py-4">
                <Navigation
                  currentPath={currentPath}
                  handleNavigationChange={handleNavigationChange}
                />
                <Search onSearchSubmit={onSearchSubmit} />
              </div>
            </nav>
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
